### ISSUE TITLE
Cannot restore from proget feed

### ISSUE THREAD

**Issue by endeffects** [Inedo/proget-docker#11]
I tried to restore my .net core web application running within a docker container by using your proget container. But i'm allways gettings timeouts. Both containers running within the same network. I've created a nuget.org connector for my feed "Packages". Also i tried to enable and disable the internal proxy.

```
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://172.19.0.2:80/nuget/Packages/FindPackagesById()?id='Scrutor'&semVerLevel=2.0.0'.
  The HTTP request to 'GET http://172.19.0.2/nuget/Packages/FindPackagesById()?id='Scrutor'&semVerLevel=2.0.0' has timed out after 100000ms.
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://172.19.0.2:80/nuget/Packages/FindPackagesById()?id='Swashbuckle.AspNetCore'&semVerLevel=2.0.0'.
  The HTTP request to 'GET http://172.19.0.2/nuget/Packages/FindPackagesById()?id='Swashbuckle.AspNetCore'&semVerLevel=2.0.0' has timed out after 100000ms.
```

I tried different sources for the restore within the build process of my webapp.

```
RUN dotnet restore "WebApp/WebApp.csproj" -s "http://172.19.0.2:80/nuget/Packages/"
RUN dotnet restore "WebApp/WebApp.csproj" -s "http://proget/nuget/Packages/"
```

**My ProGet Compose File**

```
version: '3.7'

volumes:
  database:
  packages:
  extensions:

networks:
  proget_internal_net:
    name: proget_internal_net
    driver: bridge
  proget_isolated_net:
    name: proget_isolated_net
    driver: bridge
    internal: true

services:
  proget:
    image: inedo/proget:latest
    container_name: proget
    restart: always
    environment:
      - PROGET_DATABASE=Host=proget_db; Database=proget; Username=proget; Password=secret;
    volumes:
      - packages:/var/proget/packages
      - extensions:/var/proget/extensions
    ports:
      - 80:80
    networks: 
      - proget_internal_net
      - proget_isolated_net
    depends_on:
      - proget_db

  proget_db:
    image: postgres:9.5
    container_name: proget_db
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=proget
      - POSTGRES_USER=proget
      - POSTGRES_PASSWORD=secret
    networks: 
      - proget_isolated_net

```

**My WebApplication Compose File**

```
version: '3.7'

networks:
  proget_internal_net:
    external: true

services:
  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44347
    ports:
      - "55600:80"
      - "44347:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks: 
      - proget_internal_net
```

**My WebApplication Docker File**

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-alpine AS base
WORKDIR /app

# Expose ports
EXPOSE 80
EXPOSE 443

# Copy necessary files
FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine AS build
WORKDIR /src
COPY ["WebApp/WebApp.csproj", "WebApp/"]

# Restore packages
RUN dotnet restore "WebApp/WebApp.csproj" -s "http://172.19.0.2:80/nuget/Packages/"
#RUN dotnet restore "WebApp/WebApp.csproj" -s "http://proget/nuget/Packages/" # also tried this

# Copy everything else and build
COPY . .

# Build runtime image
WORKDIR "/src/WebApp"
RUN dotnet build "WebApp.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "WebApp.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .

# Start
ENTRYPOINT ["dotnet", "WebApp.dll"]


```

**Comment by endeffects** [comment]
I found the problem after days. The docker build process 
had no access to the network while building.

This can be fixed by setting up the network for build:

```
version: '3.7'

services:
  WebApp:
    image: ${DOCKER_REGISTRY-}WebApp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
      network: proget-internal-net
```
