### ISSUE TITLE
Docker container fails to start

### ISSUE THREAD

**Issue by rose-a** [Inedo/proget-docker#8]
Hi, I have your docker container running in a *docker-compose* environment which was updated 10h ago (to `5.2.0`).

Since then the proget container fails to start with the following error message:

```txt
/bin/sh: 1: Syntax error: Unterminated quoted string
```

The `docker-compose.yml` looks as follows:

```yml
proget:
    image: inedo/proget
    container_name: proget
    environment:
      - VIRTUAL_HOST=<FQDN>
    volumes:
      - /srv/proget/packages:/var/proget/packages
      - /srv/proget/extensions:/var/proget/extensions
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8787:80'
    links:
      - proget-postgres
    restart: always

  proget-postgres:
    image: postgres:9.5
    container_name: proget-postgres
    volumes:
      - /srv/proget/db:/var/lib/postgresql/data
    restart: always
```

After reverting to `inedo/proget:5.1.23` the setup works fine again.
